// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-wox7fd5SJ3xR5ooWJM3BneE_hdR9Nh0',
    appId: '1:1008791874080:web:5f1d8779470de8b8436a45',
    messagingSenderId: '1008791874080',
    projectId: 'redditclone-f47f0',
    authDomain: 'redditclone-f47f0.firebaseapp.com',
    storageBucket: 'redditclone-f47f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDApP48_duytNKKvGI1Swbwp-k8OFiWkX8',
    appId: '1:1008791874080:android:ae1ba7ceddc326f8436a45',
    messagingSenderId: '1008791874080',
    projectId: 'redditclone-f47f0',
    storageBucket: 'redditclone-f47f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxqPqcVLXu4ue3bNw3N5EA4vEKwPpzGv4',
    appId: '1:1008791874080:ios:738c986a2f1c4f90436a45',
    messagingSenderId: '1008791874080',
    projectId: 'redditclone-f47f0',
    storageBucket: 'redditclone-f47f0.firebasestorage.app',
    iosBundleId: 'com.example.redditclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxqPqcVLXu4ue3bNw3N5EA4vEKwPpzGv4',
    appId: '1:1008791874080:ios:738c986a2f1c4f90436a45',
    messagingSenderId: '1008791874080',
    projectId: 'redditclone-f47f0',
    storageBucket: 'redditclone-f47f0.firebasestorage.app',
    iosBundleId: 'com.example.redditclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-wox7fd5SJ3xR5ooWJM3BneE_hdR9Nh0',
    appId: '1:1008791874080:web:dc397f9b440d865b436a45',
    messagingSenderId: '1008791874080',
    projectId: 'redditclone-f47f0',
    authDomain: 'redditclone-f47f0.firebaseapp.com',
    storageBucket: 'redditclone-f47f0.firebasestorage.app',
  );
}
